export const RESET_API_RESULT = "RESET_API_RESULT";
export const UPDATEGLOBALSTATEVARIABLE="UPDATEGLOBALSTATEVARIABLE";
//User
export const CHECKCRED = "CHECKCRED";
export const GETUSERDET = "GETUSERDET";
export const UPDATEUSERDET = "UPDATEUSERDET";
export const UPDATEPASSWORD = "UPDATEPASSWORD";
export const LOGOUT = "LOGOUT";
export const UPDATEUSERIDANDISWEB = "UPDATEUSERIDANDISWEB";
export const VERIFYOLDPASSWORD = "VERIFYOLDPASSWORD";
export const GETUSERPICTURE="GETUSERPICTURE";
export const SENDEMAILOTP="SENDEMAILOTP";
export const SENDMOBILEOTP="SENDMOBILEOTP";
//Country
export const GETCOUNTRIES = "GETCOUNTRIES";
export const SAVECOUNTRY = "SAVECOUNTRY";
export const DELETECOUNTRY = "DELETECOUNTRY";
export const SAVEBULKCOUNTRY = "SAVEBULKCOUNTRY";
//State
export const GETSTATES = "GETSTATES";
export const SAVESTATE = "SAVESTATE";
export const DELETESTATE = "DELETESTATE";
export const SAVEBULKSTATES = "SAVEBULKSTATES";
//Currency
export const GETBASECURRENCIES = "GETBASECURRENCIES";
export const GETBASECURRENCIEBYCODE = "GETBASECURRENCIEBYCODE";
export const SAVEBASECURRENCY = "SAVEBASECURRENCY";
export const DELETEBASECURRENCY = "DELETEBASECURRENCY";
export const SAVEBULKCURRENCIES = "SAVEBULKCURRENCIES";
//HSN Code
export const GETHSNCODES = "GETHSNCODES";
export const SAVEHSNCODE = "SAVEHSNCODE";
export const DELETEHSNCODE = "DELETEHSNCODE";
export const SAVEBULKHSNCODE = "SAVEBULKHSNCODE";
//GST Treatment
export const GETGSTTREATMENTS = "GETGSTTREATMENTS";
export const SAVEGSTTREATMENT = "SAVEGSTTREATMENT";
export const DELETEGSTTREATMENT = "DELETEGSTTREATMENT";
export const SAVEBULKGSTTREATMENT = "SAVEBULKGSTTREATMENT";
//****Masters */
//SALUTATION
export const GETSALUTATIONS = "GETSALUTATIONS";
export const SAVESALUTATION = "SAVESALUTATION";
export const DELETESALUTATION = "SAVESALUTATION";
//INDUSTRY TYPE
export const GETINDUSTRYTYPES = "GETINDUSTRYTYPES";
export const SAVEINDUSTRYTYPE = "SAVEINDUSTRYTYPE";
export const DELETEINDUSTRYTYPE = "DELETEINDUSTRYTYPE";
export const SAVEBULKINDUSTRYTYPE = "SAVEBULKINDUSTRYTYPE";
//BUSINESS TYPE
export const GETBUSINESSTYPES = "GETBUSINESSTYPES";
export const SAVEBUSINESSTYPE = "SAVEBUSINESSTYPE";
export const DELETEBUSINESSTYPE = "DELETEBUSINESSTYPE";
export const SAVEBULKBUSTYPE = "SAVEBULKBUSTYPE";

//Fiscal Year
export const GETFISCALYEARS = "GETFISCALYEARS";
export const SAVEFISCALYEAR = "SAVEFISCALYEAR";
export const DELETEFISCALYEAR = "DELETEFISCALYEAR";

//Language
export const GETLANGUAGES = "GETLANGUAGES";
export const SAVELANGUAGE = "SAVELANGUAGE";
export const DELETELANGUAGE = "DELETELANGUAGE";
export const SAVEBULKLANGUAGE = "SAVEBULKLANGUAGE";

//Date Format
export const GETDATEFORMATS = "GETDATEFORMATS";
export const SAVEDATEFORMAT = "SAVEDATEFORMAT";
export const DELETEDATEFORMAT = "DELETEDATEFORMAT";

//Tax Preference
export const GETTAXPREFERENCES = "GETTAXPREFERENCES";
export const SAVETAXPREFERENCE = "SAVETAXPREFERENCE";
export const DELETETAXPREFERENCE = "DELETETAXPREFERENCE";

//******Static Drop Down
export const GETSTARTMONTHLIST = "GETSTARTMONTHLIST";
export const GETGENDERLIST = "GETGENDERLIST";
export const GETDECIMALLIST = "GETDECIMALLIST";
export const GETFORMATLIST = "GETFORMATLIST";
export const UPLOADMASTERTYPELIST = "UPLOADMASTERTYPELIST";
